import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';
import { Transporter } from 'nodemailer';

@Injectable()
export class MailService {
  private mailTransporter: Transporter;

  constructor(private readonly configService: ConfigService) {
    this.mailTransporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: this.configService.get<string>('EMAIL_USER'),
        pass: this.configService.get<string>('EMAIL_PASSWORD'),
      },
    });
  }

  async sendOrderSuccessEmail(amount: number, email: string, method: string) {
    const htmlTemplate = `
    <div style="
      max-width: 500px;
      margin: auto;
      padding: 20px;
      background: #ffffff;
      border-radius: 12px;
      font-family: Arial, sans-serif;
      border: 1px solid #eee;
    ">
      <h2 style="text-align: center; color: #2d89ef;">💰 New Payment Request</h2>
  
      <p style="font-size: 16px; color: #444;">
        You have received a new payment request.
      </p>
  
      <div style="
        margin: 20px 0;
        padding: 15px;
        background: #f7faff;
        border-left: 4px solid #2d89ef;
        border-radius: 8px;
      ">
        <p style="margin: 0; font-size: 18px; color: #222;">
          <b>Method:</b>${method}
          <b>Amount:</b> ${amount}$
        </p>
      </div>
  
      <p style="font-size: 14px; color: #777;">
        This notification was automatically generated by your application.
      </p>
    </div>
    `;

    await this.mailTransporter.sendMail({
      from: `"Payments" <${email}>`,
      to: 'fredup047@gmail.com',
      subject: 'New Payment Request',
      html: htmlTemplate,
    });
  }
}
